export const CHOOSE_ROLE = 'CHOOSE_ROLE';

export const CHOOSE_IMG_DOG = 'CHOOSE_IMG_DOG';
export const CHOOSE_BREED_DOG = 'CHOOSE_BREED_DOG';

export const SAGA_FETCH_RANDOM_DOG = 'SAGA_FETCH_RANDOM_DOG'